"""Adiciona coluna telefone

Revision ID: 980e265ba51b
Revises: 
Create Date: 2025-02-27 15:26:49.496398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '980e265ba51b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aniversario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefone', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aniversario', schema=None) as batch_op:
        batch_op.drop_column('telefone')

    # ### end Alembic commands ###
